### ISSUE TITLE
Output is always 2048x1024

### ISSUE THREAD

**Issue by eosrei** [Xyene/cube2sphere#2]
* Ubuntu 16.04
* Blender 2.76b
* cube2sphere from pip

Works perfect! Except the output resolution is always 2048x1024. I checked the `projector.blend` file and saw that's the default image size. The settings aren't being transferred to Blender correctly. Manually changing the render resolution to 8192x4096@50% worked for my project.

**Comment by Xyene** [comment]
Thanks for reporting this! @BorisChumichev was kind enough to provide a solution, so I've bumped the project version number to 0.1.8 and uploaded a new package to PyPi.
