### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by aeqm** [Xyene/cube2sphere#6]
Blender 2.81a
Python 3.7.4
windows 10

Hello Xyene, 
thanks a lot for your script

I am trying to install using pip install cube2sphere but get this

C:\WINDOWS\system32>pip install cube2sphere
Collecting cube2sphere
  Using cached cube2sphere-0.1.8.zip (150 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\alejandro\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ALEJAN~1\\AppData\\Local\\Temp\\pip-install-am3kkxig\\cube2sphere\\setup.py'"'"'; __file__='"'"'C:\\Users\\ALEJAN~1\\AppData\\Local\\Temp\\pip-install-am3kkxig\\cube2sphere\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ALEJAN~1\AppData\Local\Temp\pip-install-am3kkxig\cube2sphere\pip-egg-info'
         cwd: C:\Users\ALEJAN~1\AppData\Local\Temp\pip-install-am3kkxig\cube2sphere\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ALEJAN~1\AppData\Local\Temp\pip-install-am3kkxig\cube2sphere\setup.py", line 4, in <module>
        import ez_setup
      File "C:\Users\ALEJAN~1\AppData\Local\Temp\pip-install-am3kkxig\cube2sphere\ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I´m not the most efficient user with coding but will try my best to fix this if there would be a solution

Thanks in advance

**Comment by Xyene** [comment]
Hi! 

Thanks for your interest in this project :)

Unfortunately, I have not gotten around to updating it to Python 3 (despite Python 2 being EOL now), so it won't work there.

**Comment by Xyene** [comment]
This should be fixed as of https://github.com/Xyene/cube2sphere/commit/5654c23ea398ecb4b69344dc14b747bfaa8bb28a if installing through git. I'll try to rebuild the PyPI packages.
